baseURL = "https://cpvlordelo.github.io"
title   = "Carlos Lordelo"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 20
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Carlos Lordelo"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "Jan"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # Metadata mostly used in document's head
  # 
  description = "Welcome to Carlos Lordelo's personal webpage"
  keywords = ""
  images = [""]

  # Home subtitle of the index page.
  #
  # homeSubtitle = "Carlos Lordelo"

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  #
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false

  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Sharing buttons
  #
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  #
  enableSharingButtons = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  #
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  #
  justifyContent = true  # Set "text-align: justify" to .post-content.

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = true
    rss = false
    copyright = false
    author = true

    topText = []
    bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a> theme"]
            #"Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "3s"

  # Commento is more than just a comments widget you can embed — 
  # it’s a return to the roots of the internet. 
  # An internet without the tracking and invasions of privacy. 
  # An internet that is simple and lightweight. 
  # An internet that is focused on interesting discussions, not ads. 
  # A better internet.
  # Uncomment this to enable Commento.
  #
  # [params.commento]
  #   url = ""

  # Uncomment this if you want a portrait on your start page
  #
   [params.portrait]
     path     = "/img/photo2.jpg"
     alt      = "Portrait"
     maxWidth = "200px"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/cpvlordelo"

  [[params.social]]
    name = "email"
    url  = "mailto:c.p.viannalordelo@qmul.ac.uk"

  [[params.social]]
    name = "github"
    url  = "https://github.com/cpvlordelo"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/lordelo-carlos"

[languages]
  [languages.en]
    title = "Carlos Lordelo"
    homeSubtitle  = "Audio Signal Processing and ML Engineer"
    subtitle = "Audio Signal Processing and ML Engineer"
    weight = 1.0
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        weight = 1.0
        url = "about/"

      [[languages.en.menu.main]]
        identifier = "publications"
        name = "Publications"
        weight = 2.0
        url = "publications/"

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        weight = 3.0
        url = "projects/"
        
  [languages.pt-br]
      title = "Titulo Portugues"
      homeSubtitle  = "Aprendizado de máquina"
      subtitle = "Aprendizado de Máquina"
      weight = 1.0
      copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    
    [languages.pt-br.menu]
      [[languages.pt-br.menu.main]]
        identifier = "about"
        name = "Sobre"
        weight = 1.0
        url = "pt-br/about/"
      [[languages.pt-br.menu.main]]
        identifier = "publications"
        name = "Publicações"
        weight = 2.0
        url = "pt-br/publications/"
      [[languages.pt-br.menu.main]]
        identifier = "projects"
        name = "Projetos"
        weight = 3.0
        url = "pt-br/projects/"

#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name       = "About"
#    url        = "about/"
#  [[menu.main]]
#    identifier = "publications"
#    name       = "Publications"
#    url        = "publications/"
#  [[menu.main]]
#    identifier = "projects"
#    name       = "Projects"
#    url        = "projects/"
    
